version: '3.9'
#####
services:
  dartserve:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Dart ilovangiz 8080 portda tinglaydi
    env_file:
      - .env  # Muhit o'zgaruvchilari uchun .env faylni ulash
