version: '3.9'
services:
  tmed_telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5000:8080
    environment:
      db_host: ""
      db_port: ""
      db_database: ""
      db_username: ""
      db_password: ""
      tg_token: ""
      tmed_bot_token: ""
      sq_bot_token: ""
