version: '3.8'
#####
services:
  dartserve:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - tmed_tg_network
    ports:
      - "8080:8080"  # Assuming your Dart application listens on port 8080


