name: tmed_tg
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  hive: ^2.2.3
  postgres: ^3.2.1
  qr_image: ^1.0.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_router_generator: ^1.1.0
  shelf_swagger_ui: ^1.0.0+2
  sqlite3: ^2.4.3
  teledart: ^0.6.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
