version: '3.9'
services:
  tmed_telegram_bot:
    build:
      context: .
      dockerfile: ../Dockerfile
    ports:
      - 5000:8080
    environment:
      db_host: ""
      db_port: ""
      db_database: ""
      db_username: ""
      db_password: ""